# Taps
tap "metalbear-co/mirrord"
tap "snyk/tap"
tap "txn2/tap"

# CLI tools
brew "actionlint"
brew "ast-grep"
brew "awscli"
brew "bat"
brew "bat-extras"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "helm"
brew "jq"
brew "k9s"
brew "lazygit"
brew "kubernetes-cli"
brew "python@3.12"
brew "ripgrep"
brew "rtk"
brew "shellcheck"
brew "stern"
brew "zoxide"
brew "zsh"
brew "metalbear-co/mirrord/mirrord"
brew "snyk/tap/snyk"
brew "txn2/tap/kubefwd"

# GUI apps
cask "bruno"
cask "claude-code"
cask "codex"
cask "git-credential-manager"
cask "iterm2"
cask "rancher"

# Adopted from manual installs
cask "appcleaner"
cask "chatgpt"
cask "dbeaver-community"
cask "firefox"
cask "google-chrome"
cask "lens"
cask "openvpn-connect"
cask "redis-insight"
cask "sourcetree"
cask "visual-studio-code"

# VSCode extensions
vscode "alefragnani.project-manager"
vscode "anthropic.claude-code"
vscode "bierner.lit-html"
vscode "bierner.markdown-mermaid"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "datadog.datadog-vscode"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "frigus02.vscode-sql-tagged-template-literals-syntax-only"
vscode "github.vscode-github-actions"
vscode "jasonnutter.search-node-modules"
vscode "meganrogge.template-string-converter"
vscode "metalbear.mirrord"
vscode "ms-azuretools.vscode-containers"
vscode "nhoizey.gremlins"
vscode "oderwat.indent-rainbow"
vscode "openai.chatgpt"
vscode "pflannery.vscode-versionlens"
vscode "redhat.vscode-yaml"
vscode "runem.lit-plugin"
vscode "snyk-security.snyk-vulnerability-scanner"
vscode "thedangander.jsonl-lab"
vscode "usernamehw.errorlens"
vscode "vitest.explorer"
vscode "yoavbls.pretty-ts-errors"
